### PR TITLE
Changed up model structure, similar to MNIST CNN

### PR DESCRIPTION
**Pull request by CharlieHVu**
Achieves~99% accuracy, needs testing however. Split dataset for training/validation/testing. Try 60/20/20.

### CODE REVIEW

**Comment by CharlieHVu** [comment]
Great job, Charlie.

**Comment by CharlieHVu** [comment]
Thanks, Charlie. You're looking good.

**Comment by CharlieHVu** [comment]
You too.

**Comment by CharlieHVu** [comment]
You're too kind. Such a great person.

**Comment by CharlieHVu** [comment]
No, you're a great person!

**Review by kkworden — APPROVED** [review]
Looks good. I don't see why overfitting would occur with this model.

**Pull request merged**
